stages:
  - build
  - deploy

image: debian:trixie

build:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  before_script:
    - apt-get update
    - apt-get install python3-venv python3-pip python3 -y
    - cd documentation/
    - python3 -m venv .venv/
    - source .venv/bin/activate
    - pip3 install -r requirements.txt
  script:
    - cd documentation/
    - source .venv/bin/activate
    - make html
    - tar cf $CI_DOCS_ARCHIVE -C build/html/ .
    - mv build/ ../.
    - mv $CI_DOCS_ARCHIVE ../.
  artifacts:
    paths:
      - build
      - $CI_DOCS_ARCHIVE

deploy:
  variables:
    GIT_STRATEGY: none
  dependencies:
    - build
  stage: deploy
  tags: ['docs']
  script: echo 'Deploying docs'
  artifacts:
    paths:
      - $CI_DOCS_ARCHIVE
